---
version: "3.7"

# This Docker composition file is used to build and test the container

secrets:
  admiral_yml:
    file: ./src/secrets/admiral.yml
  mongo_root_passwd_txt:
    file: ./src/secrets/mongo-root-passwd.txt
  redis_conf:
    file: ./src/secrets/redis.conf
  sslmate_api_key_txt:
    file: ./src/secrets/sslmate-api-key.txt

x-admiral-template: &admiral-template
  build:
    context: .
    dockerfile: Dockerfile
  deploy:
    mode: replicated
    replicas: 5
  environment:
    ADMIRAL_CONFIG_FILE: "/run/secrets/admiral.yml"
    ADMIRAL_CONFIG_SECTION: dev-mode
    ADMIRAL_WORKER_NAME: dev
  image: cisagov/admiral
  init: true
  secrets:
    - source: admiral_yml
      target: admiral.yml
    - source: sslmate_api_key_txt
      target: sslmate-api-key.txt
  volumes:  # map for development only, comment out otherwise
    - ./src/admiral:/usr/src/admiral/admiral

services:
  example:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/example
    init: true
    restart: "no"
    environment:
      - ECHO_MESSAGE=Hello World from docker compose!
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    secrets:
      - source: quote_txt
        target: quote.txt

  example-version:
    # Run the container to collect version information
    image: cisagov/example
    init: true
    restart: "no"
    command: --version
